# permissions for end users to view opencgacommunities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opencgacommunity-viewer-role
rules:
- apiGroups:
  - opencga.zetta.com
  resources:
  - opencgacommunities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opencga.zetta.com
  resources:
  - opencgacommunities/status
  verbs:
  - get
