---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opencga.zetta.com
  resources:
  - opencgacommunities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opencga.zetta.com
  resources:
  - opencgacommunities/finalizers
  verbs:
  - update
- apiGroups:
  - opencga.zetta.com
  resources:
  - opencgacommunities/status
  verbs:
  - get
  - patch
  - update
