apiVersion: opencga.zetta.com/v1
kind: OpenCGACommunity
metadata:
  name: opencgacommunity-specify-readiness-probe-values
spec:
  members: 3
  automationConfig:
    processes:
      - name: opencga-rest-1
        disabled: true
  type: OpencgaClient
  version: "2.2.0"
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: true
      certificateKeySecretRef:
        name: tls-secret-name
      caConfigMapRef:
        name: tls-ca-configmap-name
  statefulSet:
    spec:
      template:
        # label the pod which is used by the "labelSelector" in podAntiAffinty
        # you can label it witch some other labels as well -- make sure it change the podAntiAffinity labelselector accordingly
        labels:
          app: opencga-rest
        spec:
          #  Hostpath volumes are owned by root
          #  but MongoDB containers run as non root
          #  so we use an init container to change the owner of
          #  the directory (init containers run as root)
          initContainers:
          - command:
              - chown
              - -R
              - "2000"
              - /data
            image: busybox
            volumeMounts:
            - mountPath: /data
              name: data-volume
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            name: change-dir-permissions
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - opencga
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: opencga-rest
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
            - name: opencga-agent
              readinessProbe:
                failureThreshold: 50
                initialDelaySeconds: 10
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
          selector:
            matchLabels:
              # We set this labels when creating the volume
              # (see below)
              type: data
          storageClassName: default
      - metadata:
          name: logs-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8G
          selector:
            matchLabels:
              type: logs
          storageClassName: default
  additionalOpenCGAConfig:
    # the additional config passed to the mongod process can be specified
    # either in nested or dot notation
    ldpa.ip: 10.0.14.1
    net:
      port: 636
---
# Here we create 6 PVs: two for each ReplicaSet member
# (one for data, one for logs)
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: data
    name: data-volume-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-data-0
      type: ""
    nodeAffinity:
      required:
        # This is just an example for matchexpression
        # This field is required depends on the specific
        # of the environment the resource is deployed in
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: data
    name: data-volume-1
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-data-1
      type: ""
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Available
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: data
    name: data-volume-2
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-data-2
      type: ""
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: logs
    name: logs-volume-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-logs-0
      type: ""
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: logs
    name: logs-volume-1
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-logs-1
      type: ""
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: logs
    name: logs-volume-2

  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8G
    hostPath:
      path: /opt/data/opencga-logs-2
      type: ""
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
kind: List
---
